-- ==========================================
-- ARC COFFEE SHOP - FULL DATABASE SCHEMA
-- ==========================================
-- Safe for fresh AND existing Supabase projects.
-- Run the entire script in Supabase → SQL Editor.


-- ==========================================
-- 1. Cafes (Base table that everything links to)
-- ==========================================
CREATE TABLE IF NOT EXISTS cafes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  logo_url TEXT,
  primary_color TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- ==========================================
-- 2. Menu Items
-- ==========================================
CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL NOT NULL,
  category TEXT NOT NULL,
  badge TEXT,
  sort_order INTEGER DEFAULT 0,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- ==========================================
-- 3. Employees (Staff Directory)
-- ==========================================
CREATE TABLE IF NOT EXISTS employees (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  phone TEXT,
  pin_code TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add columns if table was created from an older schema
ALTER TABLE employees ADD COLUMN IF NOT EXISTS salary DECIMAL DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS shift TEXT DEFAULT 'morning';


-- ==========================================
-- 4. Shifts (Attendance & Scheduling)
-- ==========================================
CREATE TABLE IF NOT EXISTS shifts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  shift_type TEXT NOT NULL,
  status TEXT NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE shifts DROP CONSTRAINT IF EXISTS shifts_employee_id_fkey;
ALTER TABLE shifts
  ADD CONSTRAINT shifts_employee_id_fkey
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;

ALTER TABLE shifts DROP CONSTRAINT IF EXISTS shifts_employee_date_type_unique;
ALTER TABLE shifts
  ADD CONSTRAINT shifts_employee_date_type_unique
  UNIQUE (employee_id, date, shift_type);


-- ==========================================
-- 5. Inventory Items (Stock Registry)
-- ==========================================
CREATE TABLE IF NOT EXISTS inventory_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  unit TEXT NOT NULL,
  current_stock DECIMAL NOT NULL DEFAULT 0,
  min_stock DECIMAL NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- ==========================================
-- 6. Inventory Transactions (Stock In / Stock Out logs)
-- ==========================================
CREATE TABLE IF NOT EXISTS inventory_transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  type TEXT NOT NULL,
  quantity DECIMAL NOT NULL,
  note TEXT,
  date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- ==========================================
-- 7. Purchases (Vendor Cost Tracking)
-- ==========================================
CREATE TABLE IF NOT EXISTS purchases (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  supplier_name TEXT NOT NULL,
  quantity DECIMAL NOT NULL,
  unit_cost DECIMAL NOT NULL,
  total_cost DECIMAL NOT NULL,
  date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- ==========================================
-- 8. Bookings (Customer Table Reservations)
-- ==========================================
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  customer_phone TEXT,
  guests_count INTEGER NOT NULL,
  booking_date DATE NOT NULL,
  booking_time TIME NOT NULL,
  status TEXT DEFAULT 'pending',
  special_requests TEXT,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Upgrade old booking columns → app column names
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'customer_name'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'guest_name'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN customer_name TO guest_name;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'customer_phone'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'guest_phone'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN customer_phone TO guest_phone;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'guests_count'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'guest_count'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN guests_count TO guest_count;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_date'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'date'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN booking_date TO date;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'booking_time'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'time'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN booking_time TO time;
  END IF;
END $$;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS booking_ref TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS guest_name TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS guest_phone TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS guest_count INTEGER;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS time TIME;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'regular';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS occasion TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS addons JSONB DEFAULT '[]'::jsonb;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS sticker_text TEXT;


-- ==========================================
-- 9. Special Add-ons (for special bookings)
-- ==========================================
CREATE TABLE IF NOT EXISTS special_addons (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price DECIMAL NOT NULL DEFAULT 0,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  CONSTRAINT special_addons_cafe_name_unique UNIQUE (cafe_id, name)
);


-- ==========================================
-- INDEXES
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_menu_items_cafe_id ON menu_items(cafe_id);
CREATE INDEX IF NOT EXISTS idx_employees_cafe_id ON employees(cafe_id);
CREATE INDEX IF NOT EXISTS idx_employees_cafe_active ON employees(cafe_id, is_active);
CREATE INDEX IF NOT EXISTS idx_shifts_cafe_date ON shifts(cafe_id, date);
CREATE INDEX IF NOT EXISTS idx_inventory_items_cafe_id ON inventory_items(cafe_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_cafe_id ON inventory_transactions(cafe_id);
CREATE INDEX IF NOT EXISTS idx_purchases_cafe_id ON purchases(cafe_id);
CREATE INDEX IF NOT EXISTS idx_bookings_cafe_id ON bookings(cafe_id);
CREATE INDEX IF NOT EXISTS idx_bookings_cafe_status ON bookings(cafe_id, status);
CREATE INDEX IF NOT EXISTS idx_special_addons_cafe_id ON special_addons(cafe_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'date'
  ) THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bookings_cafe_date ON bookings(cafe_id, date)';
  END IF;
END $$;


-- ==========================================
-- DISABLE ROW LEVEL SECURITY (RLS)
-- (Allows your custom .env login to work)
-- ==========================================
ALTER TABLE cafes DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE shifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE special_addons DISABLE ROW LEVEL SECURITY;


-- ==========================================
-- SEED DATA
-- ==========================================
INSERT INTO cafes (id, name, slug)
VALUES (1, 'Arc Downtown', 'arc-downtown')
ON CONFLICT (id) DO NOTHING;

INSERT INTO special_addons (cafe_id, name, price, is_available)
VALUES
  (1, 'Balloon Bouquet', 25, true),
  (1, 'Celebration Cake', 45, true),
  (1, 'Fresh Flowers', 30, true),
  (1, 'Custom Banner', 20, true)
ON CONFLICT (cafe_id, name) DO NOTHING;

NOTIFY pgrst, 'reload schema';
