-- ==========================================
-- UPGRADE: old schema → app-compatible schema
-- ==========================================
-- Run this in Supabase → SQL Editor if you already
-- created tables from the original SQL you were given.
-- Safe to run more than once.


-- Employees: Staff page needs salary + shift preference
ALTER TABLE employees ADD COLUMN IF NOT EXISTS salary DECIMAL DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS shift TEXT DEFAULT 'morning';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'employees_shift_check'
  ) THEN
    ALTER TABLE employees
      ADD CONSTRAINT employees_shift_check
      CHECK (shift IN ('morning', 'evening', 'both'));
  END IF;
END $$;


-- Shifts: named FK so Supabase can join shifts ↔ employees
ALTER TABLE shifts DROP CONSTRAINT IF EXISTS shifts_employee_id_fkey;
ALTER TABLE shifts
  ADD CONSTRAINT shifts_employee_id_fkey
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;

ALTER TABLE shifts DROP CONSTRAINT IF EXISTS shifts_employee_date_type_unique;
ALTER TABLE shifts
  ADD CONSTRAINT shifts_employee_date_type_unique
  UNIQUE (employee_id, date, shift_type);


-- Bookings: rename old columns to match the app
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'customer_name'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'guest_name'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN customer_name TO guest_name;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'customer_phone'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'guest_phone'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN customer_phone TO guest_phone;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'guests_count'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'guest_count'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN guests_count TO guest_count;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'booking_date'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'date'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN booking_date TO date;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'booking_time'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'bookings' AND column_name = 'time'
  ) THEN
    ALTER TABLE bookings RENAME COLUMN booking_time TO time;
  END IF;
END $$;

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS booking_ref TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS guest_name TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS guest_phone TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS guest_count INTEGER;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS date DATE;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS time TIME;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'regular';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS occasion TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS addons JSONB DEFAULT '[]'::jsonb;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS sticker_text TEXT;


-- Special add-ons table (public booking flow)
CREATE TABLE IF NOT EXISTS special_addons (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cafe_id BIGINT NOT NULL REFERENCES cafes(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  price DECIMAL NOT NULL DEFAULT 0,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  CONSTRAINT special_addons_cafe_name_unique UNIQUE (cafe_id, name)
);

ALTER TABLE special_addons DISABLE ROW LEVEL SECURITY;

INSERT INTO special_addons (cafe_id, name, price, is_available)
VALUES
  (1, 'Balloon Bouquet', 25, true),
  (1, 'Celebration Cake', 45, true),
  (1, 'Fresh Flowers', 30, true),
  (1, 'Custom Banner', 20, true)
ON CONFLICT (cafe_id, name) DO NOTHING;

NOTIFY pgrst, 'reload schema';
